### ISSUE TITLE
PyQt5 ImportError DLL load failed

### ISSUE THREAD

**Issue by SivHMA** [issamdakir/BDENTAL-4D#1]
Hello,
I try to install your project. After pressing the Install button, I see that the required dependencies have been decompressed in the folder under user. However, after the restart, I was reminded that pyqt5.qtwigets cannot be found. First, I re-install pyqt5 through pip, and then I replace Blender's python.exe file, which does not work. Have you ever encountered such a situation?

**Comment by issamdakir** [comment]
Thank you for repporting this bug
Wich blender version are you using.
For now the dependencies work with blender 2.91 that comes with python 3.7
The blender 2.93 version have python 3.9 that needs other dependencies
files...i ll make addon update for blender 2.93 very soon

Le mer. 21 juil. 2021 à 07:59, Zhihao Ma ***@***.***> a
écrit :

**Comment by SivHMA** [comment]
I'm sorry to reply to you for such a long time.
I used the Blender 2.91 version. I replaced python.exe with WinPython3.8
Next, I'll try another version of WinPython
