### ISSUE TITLE
Guide to use JAW-TRACK ?

### ISSUE THREAD

**Issue by Vincentqyw** [issamdakir/BDENTAL-4D#6]
Thanks for your great work! I have one question about using  `JAW-TRACK`, more specifically, how to bind jaw `STL` files and markers and make the jaw move? Is there any tutorial to better understand how to make it work?

**Comment by issamdakir** [comment]
Hi thank you
In fact we were 2 on the project, I helped Dr. ilya fomenco the real creator of the project.
https://youtu.be/_Y3FhF5rx0E
In YouTube link u ll find link to it's GitHub repo

**Comment by Vincentqyw** [comment]
Thanks, I will check it.

**Comment by Gerard-sd** [comment]
Hi, I'm really excited to get you addon, but I have a problem, it won't let me install the modules. Can you help me?
